export const masterSectorMap = {
  "Tata Consultancy Services": "IT",
  "Infosys": "IT",
  "Wipro": "IT",
  "HCL Technologies": "IT",
  "Tech Mahindra": "IT",
  "LTM Ltd": "IT",
  "Mphasis": "IT",
  "Oracle Financial": "IT",
  "Tata Elxsi": "IT",
  "Coforge": "IT",
  "Persistent Systems": "IT",
  "Tanla Platforms": "IT",
  "Happiest Minds": "IT",
  "Intellect Design": "IT",
  "Route Mobile": "IT",
  "Netweb": "IT",
  "Firstsource Solutions": "IT",
  "Cyient": "IT",
  "Birlasoft": "IT",
  "Sonata Software": "IT",
  "Zensar Technologies": "IT",
  "Latent View Analytics": "IT",
  "KPIT Technologies": "IT",
  "Nazara Technologies": "IT",
  "Mastek": "IT",
  "eClerx Services": "IT",
  "Hinduja Global Solutions": "IT",
  "Subex": "IT",
  "Newgen Software": "IT",
  "MATRIMONY.COM": "IT",
  "R Systems": "IT",
  "Nucleus Software": "IT",
  "Ramco Systems": "IT",
  "Sasken Technologies": "IT",
  "Accelya Solutions": "IT",
  "Onmobile Global": "IT",
  "Cigniti Technologies": "IT",
  "RPSG Ventures": "IT",
  "Datamatics Global": "IT",
  "Xchanging Solutions": "IT",
  "Saksoft": "IT",
  "InfoBeans Technologies": "IT",
  "Moschip Technologies": "IT",
  "Kaynes Technology": "IT",
  "Syrma": "IT",
  "Xelpmoc Design": "IT",
  "Cybertech Systems": "IT",
  "D-link (India)": "IT",
  "Aurionpro Solutions": "IT",
  "Xtglobal Infotech": "IT",
  "Trigyn Technologies": "IT",
  "Allied Digital Services": "IT",
  "Zaggle Prepaid": "IT",
  "CE Info Systems": "IT",
  "Tata Technologies": "IT",
  "Tata Communications": "IT",
  "ADC India": "IT",
  "Black Box": "IT",
  "Yatra Online": "IT",
  "eMudhra": "IT",
  "Rategain Travel": "IT",
  "AccelerateBS": "IT",
  "Tracxn Technologies": "IT",
  "Techknowgreen Solutions": "IT",
  "Protean eGov": "IT",
  "Awfis Space": "IT",
  "Orient Technologies": "IT",
  "Unicommerce eSolutions": "IT",

  // ALCOHOL & BREWERIES
  "United Spirits": "ALCOHOL",
  "United Breweries": "ALCOHOL",
  "Radico Khaitan": "ALCOHOL",
  "Globus Spirits": "ALCOHOL",
  "Associated Alcohols": "ALCOHOL",
  "Som Distilleries": "ALCOHOL",
  "G M Breweries": "ALCOHOL",
  "Jubilant Agri": "ALCOHOL",
  "Sula Vineyards": "ALCOHOL",
  "Allied Blenders": "ALCOHOL",

  "Bombay Burmah": "AGRICULTURE",
  "CCL Products": "AGRICULTURE",
  "Kaveri Seed": "AGRICULTURE",
  "Venky's": "AGRICULTURE",
  "Nath Bio-Genes": "AGRICULTURE",
  "MRP Agro": "AGRICULTURE",
  "Cropster Agro": "AGRICULTURE",
  "AWL Agri": "AGRICULTURE",
  "HMA Agro": "AGRICULTURE",
  "Nova Agritech": "AGRICULTURE",
  "Harshdeep Hortico": "AGRICULTURE",
  "Shivam Chemicals": "AGRICULTURE",
  "Sanstar": "AGRICULTURE",

  "UPL": "AGROCHEMICALS",
  "PI Industries": "AGROCHEMICALS",
  "India Pesticides": "AGROCHEMICALS",
  "Coromandel International": "AGROCHEMICALS",
  "Chambal Fertilisers": "AGROCHEMICALS",
  "Fertilisers And Chemicals Travancore": "AGROCHEMICALS",
  "Gujarat Narmada Vly": "AGROCHEMICALS",
  "Rashtriya Chemicals": "AGROCHEMICALS",
  "Gujarat State Fertilizers": "AGROCHEMICALS",
  "National Fertilizers": "AGROCHEMICALS",
  "Zuari Agro Chemicals": "AGROCHEMICALS",
  "Aries Agro": "AGROCHEMICALS",
  "Madras Fertilizers": "AGROCHEMICALS",
  "Bayer CropScience": "AGROCHEMICALS",
  "Sumitomo Chemical": "AGROCHEMICALS",
  "Deepak Frtlsrs": "AGROCHEMICALS",
  "Rallis India": "AGROCHEMICALS",
  "Bharat Rasayan": "AGROCHEMICALS",
  "Dhanuka Agritech": "AGROCHEMICALS",
  "Heranba Industries": "AGROCHEMICALS",
  "Sharda Cropchem": "AGROCHEMICALS",
  "Paushak": "AGROCHEMICALS",
  "Astec LifeSciences": "AGROCHEMICALS",
  "Insecticides (India)": "AGROCHEMICALS",
  "Paradeep Phosphates": "AGROCHEMICALS",
  "Shivalik Rasayan": "AGROCHEMICALS",
  "NACL Industries": "AGROCHEMICALS",
  "3B Blackbio DX": "AGROCHEMICALS",
  "Dharmaj Crop Guard": "AGROCHEMICALS",

  // AUTO & ANCILLARY
"Samvardhana Motherson": "AUTO_ANCILLARY",
  "Bosch": "AUTO_ANCILLARY",
  "Endurance Technologies": "AUTO_ANCILLARY",
  "Exide Industries": "AUTO_ANCILLARY",
  "UNO Minda": "AUTO_ANCILLARY",
  "Amara Raja Energy": "AUTO_ANCILLARY",
  "ZF Commercial": "AUTO_ANCILLARY",
  "Timken India": "AUTO_ANCILLARY",
  "TVS Holdings": "AUTO_ANCILLARY",
  "Varroc Engineering": "AUTO_ANCILLARY",
  "Suprajit Engineering": "AUTO_ANCILLARY",
  "Craftsman Automation": "AUTO_ANCILLARY",
  "Carraro India": "AUTO_ANCILLARY",
  "CLN Energy": "AUTO_ANCILLARY",
  "Jamna Auto": "AUTO_ANCILLARY",
  "Minda Corporation": "AUTO_ANCILLARY",
  "JTEKT India": "AUTO_ANCILLARY",
  "Swaraj Engines": "AUTO_ANCILLARY",
  "Subros": "AUTO_ANCILLARY",
  "Jbm Auto": "AUTO_ANCILLARY",
  "Federal-Mogul Goetze": "AUTO_ANCILLARY",
  "Gabriel India": "AUTO_ANCILLARY",
  "Ask Automotive": "AUTO_ANCILLARY",
  "Lumax Industries": "AUTO_ANCILLARY",
  "Steel Strips Wheels": "AUTO_ANCILLARY",
  "Sansera": "AUTO_ANCILLARY",
  "Igarashi Motors": "AUTO_ANCILLARY",
  "Shanthi Gears": "AUTO_ANCILLARY",
  "Wheels India": "AUTO_ANCILLARY",
  "Sharda Motor": "AUTO_ANCILLARY",
  "Pricol": "AUTO_ANCILLARY",
  "GNA Axles": "AUTO_ANCILLARY",
  "Fiem Industries": "AUTO_ANCILLARY",
  "Munjal Showa": "AUTO_ANCILLARY",
  "Rane (Madras)": "AUTO_ANCILLARY",
  "PPAP Automotive": "AUTO_ANCILLARY",
  "Munjal Auto": "AUTO_ANCILLARY",
  "India Nippon": "AUTO_ANCILLARY",
  "Kross": "AUTO_ANCILLARY",
  "Jay Bharat Maruti": "AUTO_ANCILLARY",
  "Hindustan Composites": "AUTO_ANCILLARY",
  "Sundaram Brake": "AUTO_ANCILLARY",
  "SJS Enterprises": "AUTO_ANCILLARY",
  "Popular Vehicles": "AUTO_ANCILLARY",

 //AUTOS
  "Maruti Suzuki": "AUTO",
  "Bajaj Auto": "AUTO",
  "Tata Motors Passenger": "AUTO",
  "Tata Motors Ltd": "AUTO",
  "Hyundai Motor": "AUTO",
  "Mahindra And Mahindra": "AUTO",
  "Eicher Motors": "AUTO",
  "Hero Motocorp": "AUTO",
  "Ashok Leyland": "AUTO",
  "TVS Motor": "AUTO",
  "Escorts Kubota": "AUTO",
  "Ola Electric": "AUTO",
  "VST Tillers": "AUTO",
  "SML Mahindra": "AUTO",
  "Cartrade Tech": "AUTO",
  "Landmark Cars": "AUTO",
  "Olectra Greentech": "AUTO",
  "ECOS (India) Mobility": "AUTO",

  //BANKS
  "HDFC Bank": "BANK",
  "ICICI Bank": "BANK",
  "Kotak Mahindra Bank": "BANK",
  "State Bank of India": "BANK",
  "Axis Bank": "BANK",
  "Bank of India": "BANK",
  "Indian Bank": "BANK",
  "Indian Overseas Bank": "BANK",
  "Punjab & Sind Bank": "BANK",
  "Punjab National Bank": "BANK",
  "UCO Bank": "BANK",
  "Union Bank of India": "BANK",
  "Bank of Maharashtra": "BANK",
  "Canara Bank": "BANK",
  "Central Bank of India": "BANK",
  "Bank of Baroda": "BANK",
  "Indusind Bank": "BANK",
  "Bandhan Bank": "BANK",
  "ESAF Small Finance": "BANK",
  "Fedbank Financial": "BANK",
  "India Shelter Finance": "BANK",

  "Bajaj Finserv": "NBFC",
  "Jio Financial": "NBFC",
  "Cholamandalam Financial": "NBFC",
  "Capri Global": "NBFC",
  "JM Financial": "NBFC",
  "JSW Holdings": "NBFC",
  "Hemisphere Properties": "NBFC",
  "BF Investment": "NBFC",
  "Bajaj Finance": "NBFC",
  "SBI Cards": "NBFC",
  "Cholamandalam Investment": "NBFC",
  "Muthoot Finance": "NBFC",
  "Muthoot Microfin": "NBFC",
  "Bajaj Holdings": "NBFC",
  "Aditya Birla Capital": "NBFC",
  "L&T Finance": "NBFC",
  "Mahindra and Mahindra Financial": "NBFC",
  "Manappuram Finance": "NBFC",
  "Shriram Finance": "NBFC",
  "Motilal Oswal": "NBFC",
  "Suryoday SFB": "NBFC",
  "Poonawalla Fincorp": "NBFC",
  "CreditAccess": "NBFC",

  //CABLES
  "Polycab India": "CABLES",
  "IKIO Technologies": "CABLES",
  "Stanley Lifestyles": "CABLES",
  "Sterlite Technologies": "CABLES",
  "Finolex Cables": "CABLES",
  "KEI Industries": "CABLES",
  "Vindhya Telelinks": "CABLES",

  //CAPITAAL GOODS - ELECTRICAL
  "Siemens": "ELECTRICAL",
  "Havells India": "ELECTRICAL",
  "Cummins India": "ELECTRICAL",
  "Thermax": "ELECTRICAL",
  "Ador Welding": "ELECTRICAL",
  "ABB India": "ELECTRICAL",
  "Crompton Greaves": "ELECTRICAL",
  "CG Power": "ELECTRICAL",
  "KEC International": "ELECTRICAL",
  "V Guard": "ELECTRICAL",
  "Hitachi Energy": "ELECTRICAL",
  "Triveni Turbine": "ELECTRICAL",
  "GE Vernova": "ELECTRICAL",
  "Transrail Lighting": "ELECTRICAL",
  "Schneider Electric": "ELECTRICAL",
  "Jyoti CNC": "ELECTRICAL",
  "Apar Industries": "ELECTRICAL",
  "Inox Wind": "ELECTRICAL",
  "INOX India": "ELECTRICAL",
  "Inox Green Energy": "ELECTRICAL",
  "Shilchar Technologies": "ELECTRICAL",
  "Bharat Bijlee": "ELECTRICAL",
  "Kirloskar Brothers": "ELECTRICAL",
  "RMC Switchgears": "ELECTRICAL",
  "Marine Electricals": "ELECTRICAL",
  "Voltamp Transformers": "ELECTRICAL",
  "Transformers and Rectifiers": "ELECTRICAL",
  "Bajel Projects": "ELECTRICAL",
  "Advait Energy": "ELECTRICAL",
  "Yash Highvoltage": "ELECTRICAL",
  "Skipper Ltd": "ELECTRICAL",
  "Kaycee Industries": "ELECTRICAL",
  "Divgi TorqTransfer": "ELECTRICAL",
  "TD Power Systems": "ELECTRICAL",
  "Rishabh Instruments": "ELECTRICAL",
  "KP Green Engineering": "ELECTRICAL",
  "Centum Electronics": "ELECTRICAL",
  "L&T Technology Services": "ELECTRICAL",
  "Anup Engineering": "ELECTRICAL",
  "Mold-Tek Technologies": "ELECTRICAL",
  "B C C Fuba": "ELECTRICAL",

  //CAPITAL GOODS - NON ELECTRICAL
  "Graphite India": "NON_ELECTRICAL",
  "Grindwell Norton": "NON_ELECTRICAL",
  "Carborundum Universal": "NON_ELECTRICAL",
  "HEG": "NON_ELECTRICAL",
  "ELGI Equipments": "NON_ELECTRICAL",
  "Gmm Pfaudler": "NON_ELECTRICAL",
  "Praj Industries": "NON_ELECTRICAL",
  "Isgec Heavy Engineering": "NON_ELECTRICAL",
  "HLE Glascoat": "NON_ELECTRICAL",
  "NESCO": "NON_ELECTRICAL",
  "KSB": "NON_ELECTRICAL",
  "Greaves Cotton": "NON_ELECTRICAL",
  "ESAB India": "NON_ELECTRICAL",
  "Kirloskar Oil Engines": "NON_ELECTRICAL",
  "Action Construction Equipment": "NON_ELECTRICAL",
  "Uniparts India": "NON_ELECTRICAL",
  "Ingersoll-Rand": "NON_ELECTRICAL",
  "Shakti Pumps": "NON_ELECTRICAL",
  "Sanghvi Movers": "NON_ELECTRICAL",
  "Indo Farm Equipment": "NON_ELECTRICAL",
  "United Drilling Tools": "NON_ELECTRICAL",
  "Quest Flow Controls": "NON_ELECTRICAL",
  "Diffusion Engineers": "NON_ELECTRICAL",
  "Sunita Tools": "NON_ELECTRICAL",
  "Aeroflex Industries": "NON_ELECTRICAL",
  "Tega Industries": "NON_ELECTRICAL",
  "Alphalogic Industries": "NON_ELECTRICAL",
  "JNK India": "NON_ELECTRICAL",
  "New Swan Multitech": "NON_ELECTRICAL",
  "Gala Precision Engineering": "NON_ELECTRICAL",
  "SKF India": "NON_ELECTRICAL",
  "Rolex Rings": "NON_ELECTRICAL",
  "NRB Bearings": "NON_ELECTRICAL",
  "Sealmatic India": "NON_ELECTRICAL",
  
  //CASTINGS & FORGINGS
  "Bharat Forge": "CASTINGS_FORGINGS",
  "Sona Blw Precision Forgings": "CASTINGS_FORGINGS",
  "AIA Engineering": "CASTINGS_FORGINGS",
  "CIE Automotive India": "CASTINGS_FORGINGS",
  "Ramkrishna Forgings": "CASTINGS_FORGINGS",
  "Electrosteel Castings": "CASTINGS_FORGINGS",
  "MM Forgings": "CASTINGS_FORGINGS",
  "Maiden Forgings": "CASTINGS_FORGINGS",
  "Happy Forgings": "CASTINGS_FORGINGS",
  "Sterling Tools": "CASTINGS_FORGINGS",
  "Nelcast": "CASTINGS_FORGINGS",

  //CEMENT
  "UltraTech Cement": "CEMENT",
  "Shree Cement": "CEMENT",
  "Ambuja Cements": "CEMENT",
  "ACC Ltd": "CEMENT",
  "Dalmia Bharat": "CEMENT",
  "Ramco Cements": "CEMENT",
  "JSW Cement": "CEMENT",
  "J K Cement": "CEMENT",
  "Birla Corporation": "CEMENT",
  "Prism Johnson": "CEMENT",
  "Heidelbergcement": "CEMENT",
  "India Cements": "CEMENT",
  "JK Lakshmi Cement": "CEMENT",
  "Star Cement": "CEMENT",
  "Orient Cement": "CEMENT",
  "KCP": "CEMENT",
  "Shree Digvijay Cement": "CEMENT",
  "Mangalam Cement": "CEMENT",
  "Anjani Portland": "CEMENT",
  "Ramco Industries": "CEMENT",
  "Visaka Industries": "CEMENT",
  "Everest Industries": "CEMENT",
  "Sahyadri Industries": "CEMENT",
  "Nuvoco Vistas": "CEMENT",

  //CHEMICALS
  "Pidilite Industries": "CHEMICALS",
  "HP Adhesives": "CHEMICALS",
  "Aarti Industries": "CHEMICALS",
  "Atul Ltd": "CHEMICALS",
  "Deepak Nitrite": "CHEMICALS",
  "Tata Chemicals": "CHEMICALS",
  "Alkyl Amines": "CHEMICALS",
  "Navin Fluorine": "CHEMICALS",
  "Vinati Organics": "CHEMICALS",
  "Godrej Industries": "CHEMICALS",
  "Linde India": "CHEMICALS",
  "Castrol India": "CHEMICALS",
  "Solar Industries": "CHEMICALS",
  "BASF India": "CHEMICALS",
  "Fine Organic": "CHEMICALS",
  "Gujarat Fluorochemicals": "CHEMICALS",
  "Balaji Amines": "CHEMICALS",
  "Anupam Rasayan": "CHEMICALS",
  "Rossari Biotech": "CHEMICALS",
  "Laxmi Organic": "CHEMICALS",
  "Adv Enzyme Tech": "CHEMICALS",
  "Sudarshan Chemical": "CHEMICALS",
  "Privi Speciality": "CHEMICALS",
  "Tatva Chintan": "CHEMICALS",
  "PCBL Chemical": "CHEMICALS",
  "Gulf Oil Lubricants": "CHEMICALS",
  "Gujarat Alkalies": "CHEMICALS",
  "Nocil": "CHEMICALS",
  "Oriental Aromatics": "CHEMICALS",
  "GHCL": "CHEMICALS",
  "Camlin Fine Sciences": "CHEMICALS",
  "S H Kelkar": "CHEMICALS",
  "Neogen Chemicals": "CHEMICALS",
  "Himadri Speciality": "CHEMICALS",
  "Chemcon Speciality": "CHEMICALS",
  "I G Petrochemicals": "CHEMICALS",
  "India Glycols": "CHEMICALS",
  "Punjab Chemicals": "CHEMICALS",
  "Bodal Chemicals": "CHEMICALS",
  "Vidhi Specialty": "CHEMICALS",
  "Excel Industries": "CHEMICALS",
  "Thirumalai Chemicals": "CHEMICALS",
  "OCCL": "CHEMICALS",
  "Chembond Material": "CHEMICALS",
  "Goa Carbon": "CHEMICALS",
  "Aksharchem (India)": "CHEMICALS",
  "Asahi Songwon": "CHEMICALS",
  "Gulshan Polyols": "CHEMICALS",
  "Vishnu Chemicals": "CHEMICALS",
  "Archean Chemical": "CHEMICALS",
  "Aether Industries": "CHEMICALS",
  "Clean Science": "CHEMICALS",
  "Deepak Chemtex": "CHEMICALS",
  "JG Chemicals": "CHEMICALS",
  "Platinum Industries": "CHEMICALS",
  "Kronox Lab Sciences": "CHEMICALS",
  "Godavari Biorefineries": "CHEMICALS",

  //CERAMICS
  "Kajaria Ceramics": "CERAMICS",
  "Cera Sanitaryware": "CERAMICS",
  "Somany Ceramics": "CERAMICS",
  "AGI Greenpac": "CERAMICS",
  "Pokarna": "CERAMICS",
  "Exxaro Tiles": "CERAMICS",
  "Asian Granito": "CERAMICS",
  "Orient Bell": "CERAMICS",
  "Global Surfaces": "CERAMICS",

  //CONSTRUCTION
  "Larsen and Toubro": "CONSTRUCTION",
  "Ircon International": "CONSTRUCTION",
  "Irb Infrastructure": "CONSTRUCTION",
  "Techno Electric": "CONSTRUCTION",
  "Nirlon": "CONSTRUCTION",
  "Ashoka Buildcon": "CONSTRUCTION",
  "Likhitha Infrastructure": "CONSTRUCTION",
  "G R Infraprojects": "CONSTRUCTION",
  "Afcons Infrastructure": "CONSTRUCTION",
  "PNC Infratech": "CONSTRUCTION",
  "KNR Constructions": "CONSTRUCTION",
  "HG Infra Engineering": "CONSTRUCTION",
  "Welspun Enterprises": "CONSTRUCTION",
  "Kalpataru Projects": "CONSTRUCTION",
  "Psp Projects": "CONSTRUCTION",
  "Sadbhav Engineering": "CONSTRUCTION",
  "Indian Hume Pipe": "CONSTRUCTION",
  "Gayatri Projects": "CONSTRUCTION",
  "RPP Infra Projects": "CONSTRUCTION",
  "Vishnu Prakash R Punglia": "CONSTRUCTION",
  "Ceigall India": "CONSTRUCTION",
  "Garuda Construction": "CONSTRUCTION",
  "Udayshivakumar Infra": "CONSTRUCTION",
  "SRM Contractors": "CONSTRUCTION",
  "DMR Engineering": "CONSTRUCTION",
  "Ems Ltd": "CONSTRUCTION",
  "Vruddhi Engineering": "CONSTRUCTION",
  "DEE Development": "CONSTRUCTION",
  "Deepak Builders": "CONSTRUCTION",

  "NIIT": "EDUCATION",
  "Aptech": "EDUCATION",
  "Zee Learn": "EDUCATION",
  "Veranda Learning": "EDUCATION",

  "Honeywell Automation": "CONS_DURABLES",
  "Voltas": "CONS_DURABLES",
  "Whirlpool": "CONS_DURABLES",
  "Dixon Technologies": "CONS_DURABLES",
  "Avalon Technologies": "CONS_DURABLES",
  "Bajaj Electricals": "CONS_DURABLES",
  "TTK Prestige": "CONS_DURABLES",
  "Amber Enterprises": "CONS_DURABLES",
  "Blue Star": "CONS_DURABLES",
  "Symphony": "CONS_DURABLES",
  "KRN Heat Exchanger": "CONS_DURABLES",
  "Bosch Home Comfort": "CONS_DURABLES",
  "Orient Electric": "CONS_DURABLES",
  "IFB Industries": "CONS_DURABLES",
  "Hawkins Cookers": "CONS_DURABLES",
  "Epack Durable": "CONS_DURABLES",
  "Stove Kraft": "CONS_DURABLES",
  "Comrade Appliances": "CONS_DURABLES",
  "Genus Power": "CONS_DURABLES",
  "Maruti Interior": "CONS_DURABLES",
  "Virtuoso Optoelectronics": "CONS_DURABLES",

  //RATINGS
  "Crisil": "RATINGS",
  "ICRA": "RATINGS",
  "CARE Ratings": "RATINGS",

  //CRUDE OIL & GAS
  "Reliance Industries": "CRUDE_OIL_GAS",
  "Mangalore Refinery": "CRUDE_OIL_GAS",
  "Chennai Petroleum": "CRUDE_OIL_GAS",
  "Hindustan Oil Exploration": "CRUDE_OIL_GAS",
  "Antelopus Selan Energy": "CRUDE_OIL_GAS",
  "Aban Offshore": "CRUDE_OIL_GAS",
  "Gandhar Oil Refinery": "CRUDE_OIL_GAS",

  //JEWELLERY
  "Titan Company": "JEWELLERY",
  "Ethos": "JEWELLERY",
  "Rajesh Exports": "JEWELLERY",
  "P N Gadgil Jewellers": "JEWELLERY",
  "Vaibhav Global": "JEWELLERY",
  "PC Jeweller": "JEWELLERY",
  "Thangamayil Jewellery": "JEWELLERY",
  "Goldiam Intl": "JEWELLERY",
  "Renaissance Global": "JEWELLERY",
  "Bluestone Jewellery": "JEWELLERY",
  "Kalyan Jewellers": "JEWELLERY",
  "Senco Gold": "JEWELLERY",
  "Shanti Gold": "JEWELLERY",
  "Motisons Jewellers": "JEWELLERY",
  "Tribhovandas Bhimji": "JEWELLERY",
  "International Gemological Institute": "JEWELLERY",
  "Ashapuri Gold": "JEWELLERY",
  "Khazanchi Jewellers": "JEWELLERY",
  "Eighty Jewellers": "JEWELLERY",
  "PNGS Gargi": "JEWELLERY",
  "Dev Labtech Venture": "JEWELLERY",
  "Manoj Vaibhav Gems": "JEWELLERY",
  "Rbz Jewellers": "JEWELLERY",

  //DIVERSIFIED
  "Grasim Industries": "DIVERSIFIED",
  "Interglobe Aviation": "DIVERSIFIED",
  "SRF Ltd": "DIVERSIFIED",
  "IRCTC": "DIVERSIFIED",
  "3M India": "DIVERSIFIED",
  "DCM Shriram": "DIVERSIFIED",
  "Quess Corp": "DIVERSIFIED",
  "Teamlease Services": "DIVERSIFIED",
  "Easy Trip Planners": "DIVERSIFIED",
  "Kesoram Industries": "DIVERSIFIED",
  "Nava Limited": "DIVERSIFIED",
  "Updater Services": "DIVERSIFIED",
  "Everest Kanto Cylinder": "DIVERSIFIED",
  "Electronics Mart India": "DIVERSIFIED",

  //EDIBLE OILS
  "Patanjali Foods": "EDIBLE_OILS",
  "Gujarat Ambuja Exports": "EDIBLE_OILS",
  "Avt Natural Products": "EDIBLE_OILS",
  "Raj Oil Mills": "EDIBLE_OILS",
  "Shri Venkatesh Refineries": "EDIBLE_OILS",

  //ELECTRIC VEHICLES
  "HBL Engineering": "EV",
  "Servotech Renewable": "EV",
  "Exicom Tele-Systems": "EV",
  "Indo National": "EV",

  //GASES
  "Indraprastha Gas": "GASES",
  "Petronet LNG": "GASES",
  "Gujarat State Petronet": "GASES",
  "Mahanagar Gas": "GASES",
  "Irm Energy": "GASES",

  //FMCG
  "Asahi India Glass": "GLASS",
  "Borosil Renewables": "GLASS",
  "La Opala RG": "GLASS",
  "Borosil Ltd": "GLASS",

  //FMCG
  "Hindustan Unilever": "FMCG",
  "ITC Ltd": "FMCG",
  "Nestle India": "FMCG",
  "Dabur India": "FMCG",
  "Britannia Industries": "FMCG",
  "Godrej Consumer": "FMCG",
  "Marico": "FMCG",
  "Tata Consumer": "FMCG",
  "Procter & Gamble": "FMCG",
  "Colgate-Palmolive": "FMCG",
  "Jubilant FoodWorks": "FMCG",
  "Varun Beverages": "FMCG",
  "Emami": "FMCG",
  "Gillette India": "FMCG",
  "Hatsun Agro": "FMCG",
  "Devyani International": "FMCG",
  "Zydus Wellness": "FMCG",
  "Godrej Agrovet": "FMCG",
  "Avanti Feeds": "FMCG",
  "Galaxy Surfactants": "FMCG",
  "Jyothy Labs": "FMCG",
  "VST Industries": "FMCG",
  "KRBL": "FMCG",
  "Hindustan Foods": "FMCG",
  "Godfrey Phillips": "FMCG",
  "Bajaj Consumer Care": "FMCG",
  "Tasty Bite Eatables": "FMCG",
  "Dodla Dairy": "FMCG",
  "LT Foods": "FMCG",
  "Mrs. Bectors Food": "FMCG",
  "ADF Foods": "FMCG",
  "Heritage Foods": "FMCG",
  "Prataap Snacks": "FMCG",
  "Parag Milk Foods": "FMCG",
  "Aarti Surfactants": "FMCG",
  "Avt Natural Products": "FMCG",
  "Vadilal Industries": "FMCG",
  "Apex Frozen Foods": "FMCG",
  "Mukka Proteins": "FMCG",
  "United Foodbrands": "FMCG",
  "Bikaji Foods": "FMCG",
  "Gopal Snacks": "FMCG",
  "Sapphire Foods": "FMCG",
  "Neopolitan Pizza": "FMCG",

  //HOSPITALS & DIAGNOSTICS
  "Apollo Hospitals": "HOSPITALS",
  "Dr. Lal PathLabs": "HOSPITALS",
  "Vijaya Diagnostic": "HOSPITALS",
  "Max Healthcare": "HOSPITALS",
  "Fortis Healthcare": "HOSPITALS",
  "Metropolis Healthcare": "HOSPITALS",
  "Poly Medicure": "HOSPITALS",
  "Narayana Hrudayalaya": "HOSPITALS",
  "Krishna Institute": "HOSPITALS",
  "Aster DM Healthcare": "HOSPITALS",
  "Thyrocare": "HOSPITALS",
  "Kovai Medical Center": "HOSPITALS",
  "Jupiter Life Line": "HOSPITALS",
  "Global Health": "HOSPITALS",
  "Shalby": "HOSPITALS",
  "Dr. Agarwal's": "HOSPITALS",
  "Yatharth Hospital": "HOSPITALS",
  "Aashka Hospitals": "HOSPITALS",
  "Krsnaa Diagnostics": "HOSPITALS",
  "Suraksha Diagnostic": "HOSPITALS",
  "Rainbow Children's": "HOSPITALS",
  "Asarfi Hospital": "HOSPITALS",
  "Medi Assist": "HOSPITALS",
  "GPT Healthcare": "HOSPITALS",

  //HOTELS
  "Indian Hotels": "HOTELS",
  "EIH Ltd": "HOTELS",
  "Restaurant Brands Asia": "HOTELS",
  "Chalet Hotels": "HOTELS",
  "India Tourism Dev": "HOTELS",
  "Lemon Tree Hotels": "HOTELS",
  "Mahindra Holidays": "HOTELS",
  "EIH Associated": "HOTELS",
  "TAJ GVK": "HOTELS",
  "Apeejay Surrendra Park": "HOTELS",
  "Samhi Hotels": "HOTELS",

  //HOUSING FINANCE
  "Bajaj Housing Finance": "HOUSING_FINANCE",
  "LIC Housing Finance": "HOUSING_FINANCE",
  "Can Fin Homes": "HOUSING_FINANCE",
  "Home First Finance": "HOUSING_FINANCE",
  "Repco Home Finance": "HOUSING_FINANCE",
  "Aavas Financiers": "HOUSING_FINANCE",
  "SBFC Finance": "HOUSING_FINANCE",
  "Aptus Value Housing": "HOUSING_FINANCE",
  "Aadhar Housing Finance": "HOUSING_FINANCE",
  "Northern ARC Capital": "HOUSING_FINANCE",

  //REALTY
  "DLF": "REALTY",
  "Lodha Developers": "REALTY",
  "Godrej Properties": "REALTY",
  "Oberoi Realty": "REALTY",
  "Phoenix Mills": "REALTY",
  "Prestige Estates": "REALTY",
  "NBCC": "REALTY",
  "Brigade Enterprises": "REALTY",
  "Sobha": "REALTY",
  "Signatureglobal": "REALTY",
  "Shriram Properties": "REALTY",
  "Dilip Buildcon": "REALTY",
  "Sunteck Realty": "REALTY",
  "Embassy Developments": "REALTY",
  "Mahindra Lifespace": "REALTY",
  "Ahluwalia Contracts": "REALTY",
  "Puravankara": "REALTY",
  "Kolte-Patil": "REALTY",
  "Juniper Hotels": "REALTY",
  "Ventive Hospitality": "REALTY",
  "Suraj Estate Developers": "REALTY",
  "Samor Reality": "REALTY",
  "Kesar India": "REALTY",
  "Keystone Realtors": "REALTY",
  "Arvind Smartspaces": "REALTY",
  "Interarch Building": "REALTY",
  "Arkade Developers": "REALTY",

  //LIFE INSURANCE
  "LIC of India": "LIFE_INSURANCE",
  "HDFC Life Insurance": "LIFE_INSURANCE",
  "Sbi Life Insurance": "LIFE_INSURANCE",
  "Max Financial Services": "LIFE_INSURANCE",
  "Icici Prudential Life": "LIFE_INSURANCE",
  "ICICI Lombard": "LIFE_INSURANCE",
  "Star Health": "LIFE_INSURANCE",
  "Go Digit": "LIFE_INSURANCE",
  "Niva Bupa Health": "LIFE_INSURANCE",

  //LEATHER & FOOTWEAR
  "Relaxo Footwears": "RETAIL_LEATHER",
  "Mirza International": "RETAIL_LEATHER",
  "Liberty Shoes": "RETAIL_LEATHER",

  //RETAIL
  "Avenue Supermarts": "RETAIL",
  "Trent Ltd": "RETAIL",
  "Bata India": "RETAIL",
  "Aditya Birla Fashion": "RETAIL",
  "V-Mart Retail": "RETAIL",
  "Shoppers Stop": "RETAIL",
  "ARVIND FASHIONS": "RETAIL",
  "Baazar Style Retail": "RETAIL",
  "V2 Retail": "RETAIL",
  "Khadim India": "RETAIL",
  "Campus Activewear": "RETAIL",
  "Metro Brands": "RETAIL",

  //SHIPPING
  "Great Eastern Shipping": "SHIPPING",
  "Shipping Corporation": "SHIPPING",
  "Dredging Corporation": "SHIPPING",
  "Seamec": "SHIPPING",
  "Knowledge Marine": "SHIPPING",
  "Cargotrans Maritime": "SHIPPING",
  "CFF Fluid Control": "SHIPPING",
  "Adani Ports": "SHIPPING",
  "Gujarat Pipavav": "SHIPPING",
  "Cochin Shipyard": "SHIPPING",
  "Mazagon Dock": "SHIPPING",
  "Garden Reach Shipbuilders": "SHIPPING",

  //LOGISTICS
  "Container Corporation": "LOGISTICS",
  "Blue Dart Express": "LOGISTICS",
  "Aegis Logistics": "LOGISTICS",
  "Mahindra Logistics": "LOGISTICS",
  "TCI Express": "LOGISTICS",
  "Gateway Distriparks": "LOGISTICS",
  "Allcargo Logistics": "LOGISTICS",
  "Transport Corporation": "LOGISTICS",
  "VRL Logistics": "LOGISTICS",
  "Snowman Logistics": "LOGISTICS",
  "TVS Supply Chain": "LOGISTICS",
  "JSW Infrastructure": "LOGISTICS",
  "Delhivery": "LOGISTICS",
  "Rapid Multimodal": "LOGISTICS",
  "Western Carriers": "LOGISTICS",
  "Blackbuck": "LOGISTICS",
  "Gb Logistics Commerce": "LOGISTICS",

  //PLASTIC
  "Astral": "PLASTIC",
  "Supreme Industries": "PLASTIC",
  "EPL Ltd": "PLASTIC",
  "Prince Pipes": "PLASTIC",
  "Venus Pipes and Tubes": "PLASTIC",
  "Responsive Industries": "PLASTIC",
  "Jindal Poly Films": "PLASTIC",
  "Polyplex Corp": "PLASTIC",
  "Uflex": "PLASTIC",
  "Nilkamal": "PLASTIC",
  "Huhtamaki India": "PLASTIC",
  "Time Technoplast": "PLASTIC",
  "Jai Corp": "PLASTIC",
  "Apollo Pipes": "PLASTIC",
  "Mold-Tek Packaging": "PLASTIC",
  "Ester Industries": "PLASTIC",
  "Plastiblends India": "PLASTIC",
  "Mahindra EPC Irrigation": "PLASTIC",
  "Texmo Pipes": "PLASTIC",
  "Tokyo Plast": "PLASTIC",
  "Rubfila International": "PLASTIC",
  "Kaka Industries": "PLASTIC",
  "Chemplast Sanmar": "PLASTIC",
  "AIK Pipes": "PLASTIC",
  "Swashthik Plascon": "PLASTIC",
  "Arrow Greentech": "PLASTIC",
  
  //PAINTS
  "Asian Paints": "PAINTS",
  "Berger Paints": "PAINTS",
  "Kansai Nerolac": "PAINTS",
  "Indigo Paints": "PAINTS",
  "JSW Dulux": "PAINTS",

  //PAPER & PAPER PRODUCTS
  "JK Paper": "PAPER_CARTELS",
  "West Coast Paper": "PAPER_CARTELS",
  "Seshasayee Paper": "PAPER_CARTELS",
  "TCPL Packaging": "PAPER_CARTELS",
  "Star Paper": "PAPER_CARTELS",
  "Cello World": "PAPER_CARTELS",
  "Doms Industries": "PAPER_CARTELS",
  "Flair Writing": "PAPER_CARTELS",
  "Subam Papers": "PAPER_CARTELS",

  //PETROCHEMICALS
  "Rain Industries": "PETROCHEMICALS",
  "Supreme Petrochem": "PETROCHEMICALS",
  "Bhansali Engineering": "PETROCHEMICALS",
  "Styrenix Performance": "PETROCHEMICALS",

  //HOSPITALS & DIAGNOSTICS
  "Apollo Hospitals": "HOSPITALS",
  "Dr. Lal PathLabs": "HOSPITALS",
  "Vijaya Diagnostic": "HOSPITALS",
  "Max Healthcare": "HOSPITALS",
  "Fortis Healthcare": "HOSPITALS",
  "Metropolis Healthcare": "HOSPITALS",
  "Poly Medicure": "HOSPITALS",
  "Narayana Hrudayalaya": "HOSPITALS",
  "Krishna Institute": "HOSPITALS",
  "Aster DM Healthcare": "HOSPITALS",
  "Thyrocare": "HOSPITALS",
  "Kovai Medical Center": "HOSPITALS",
  "Jupiter Life Line": "HOSPITALS",
  "Global Health": "HOSPITALS",
  "Shalby": "HOSPITALS",
  "Dr. Agarwal's": "HOSPITALS",
  "Yatharth Hospital": "HOSPITALS",
  "Aashka Hospitals": "HOSPITALS",
  "Krsnaa Diagnostics": "HOSPITALS",
  "Suraksha Diagnostic": "HOSPITALS",
  "Rainbow Children's": "HOSPITALS",
  "Asarfi Hospital": "HOSPITALS",
  "Medi Assist": "HOSPITALS",
  "GPT Healthcare": "HOSPITALS",

  //API
  "Divi's Laboratories": "API",
  "Laurus Labs": "API",
  "IPCA Laboratories": "API",
  "J B Chemicals": "API",
  "Granules India": "API",
  "Alivus Life Sciences": "API",
  "Aarti Drugs": "API",
  "Solara Active": "API",
  "Hikal": "API",
  "IOL Chemicals": "API",
  "Tatva Chintan": "API",
  "Acutaas Chemicals": "API",
  "Shilpa Medicare": "API",
  "Neuland Laboratories": "API",
  "Marksans Pharma": "API",
  "Valiant Laboratories": "API",
  "MedPlus Health": "API",
  "Supriya Lifescience": "API",
  "Concord Biotech": "API",

  //PHARMA
  "Sun Pharmaceutical": "PHARMA",
  "Dr Reddy's": "PHARMA",
  "Cipla": "PHARMA",
  "Anthem BioSciences": "PHARMA",
  "Mankind Pharma": "PHARMA",
  "Zydus Lifesciences": "PHARMA",
  "Aurobindo Pharma": "PHARMA",
  "Lupin Ltd": "PHARMA",
  "Biocon": "PHARMA",
  "Torrent Pharmaceuticals": "PHARMA",
  "Gland Pharma": "PHARMA",
  "Alkem Laboratories": "PHARMA",
  "Abbott India": "PHARMA",
  "GlaxoSmithKline": "PHARMA",
  "Senores Pharmaceuticals": "PHARMA",
  "Pfizer": "PHARMA",
  "Syngene International": "PHARMA",
  "Alembic Pharmaceuticals": "PHARMA",
  "Sanofi India": "PHARMA",
  "Ajanta Pharma": "PHARMA",
  "Emcure Pharmaceuticals": "PHARMA",
  "Natco Pharma": "PHARMA",
  "Glenmark Pharmaceuticals": "PHARMA",
  "Sai Life Sciences": "PHARMA",
  "Suven Life Sciences": "PHARMA",
  "Jubilant Pharmova": "PHARMA",
  "Procter & Gamble Health": "PHARMA",
  "Astrazeneca Pharma": "PHARMA",
  "Eris Lifesciences": "PHARMA",
  "Strides Pharma": "PHARMA",
  "Viyash Scientific": "PHARMA",
  "F D C Ltd": "PHARMA",
  "Sigachi Industries": "PHARMA",
  "Advanced Enzyme": "PHARMA",
  "Caplin Point": "PHARMA",
  "Alembic Ltd": "PHARMA",
  "Indoco Remedies": "PHARMA",
  "Dishman Carbogen Amcis": "PHARMA",
  "Morepen Laboratories": "PHARMA",
  "Unichem Laboratories": "PHARMA",
  "Hester Biosciences": "PHARMA",
  "Amrutanjan Health Care": "PHARMA",
  "Gufic BioSciences": "PHARMA",
  "Bliss GVS Pharma": "PHARMA",
  "Entero Healthcare": "PHARMA",
  "Bajaj Healthcare": "PHARMA",
  "Ngl Fine Chem": "PHARMA",
  "Fermenta Biotech": "PHARMA",
  "Kopran Ltd": "PHARMA",
  "Windlas Biotech": "PHARMA",
  "RPG Life Sciences": "PHARMA",
  "Anuh Pharma": "PHARMA",
  "Medicamen Biotech": "PHARMA",
  "Indegene": "PHARMA",
  "Lincoln Pharmaceuticals": "PHARMA",
  "Themis Medicare": "PHARMA",
  "Albert David": "PHARMA",
  "Shelter Pharma": "PHARMA",
  "Adeshwar Meditex": "PHARMA",
  "PREVEST DENPRO": "PHARMA",
  "Hemant Surgical": "PHARMA",
  "Tarsons Products": "PHARMA",
  "Dipna Pharmachem": "PHARMA",
  "Trident Lifeline": "PHARMA",
  "Blue Jet Healthcare": "PHARMA",
  "Innova Captab": "PHARMA",
  "Magenta Lifecare": "PHARMA",
  "Nephrocare Health": "PHARMA",
  "Akums Drugs": "PHARMA",
  "Sagility": "PHARMA",

  //POWER
  "Adani Green Energy": "POWER",
  "Adani Energy Solutions": "POWER",
  "Adani Power": "POWER",
  "Tata Power Company": "POWER",
  "Torrent Power": "POWER",
  "JSW Energy": "POWER",
  "SJVN": "POWER",
  "CESC": "POWER",
  "NLC India": "POWER",
  "PTC India": "POWER",
  "BF Utilities": "POWER",
  "Promax Power": "POWER",

  //REFRACTORIES
  "RHI Magnesita India": "REFRACTORIES",
  "Vesuvius India": "REFRACTORIES",
  "IFGL Refractories": "REFRACTORIES",
  "Orient Ceratech": "REFRACTORIES",

  //RUBBER BELTS
  "Apcotex Industries": "RUBBER_BELTS",
  "Pix Transmissions": "RUBBER_BELTS",
  "Rubfila International": "RUBBER_BELTS",

  //SUGAR & ETHANOL
  "Shree Renuka Sugars": "SUGAR_ETHANOL",
  "E I D-Parry (India)": "SUGAR_ETHANOL",
  "Balrampur Chini Mills": "SUGAR_ETHANOL",
  "Triveni Engineering": "SUGAR_ETHANOL",
  "Dalmia Bharat Sugar": "SUGAR_ETHANOL",
  "Dhampur Sugar Mills": "SUGAR_ETHANOL",
  "Andhra Sugars": "SUGAR_ETHANOL",
  "Avadh Sugar & Energy": "SUGAR_ETHANOL",

  //METALS
  "JSW Steel": "METALS",
  "Tata Steel": "METALS",
  "Steel Authority of India": "METALS",
  "Jindal Steel": "METALS",
  "Apl Apollo Tubes": "METALS",
  "Shyam Metalics": "METALS",
  "Ratnamani Metals": "METALS",
  "Jindal Stainless": "METALS",
  "Welspun Corp": "METALS",
  "Mishra Dhatu Nigam": "METALS",
  "Godawari Power": "METALS",
  "Jindal SAW": "METALS",
  "Indian Metals": "METALS",
  "KIOCL": "METALS",
  "Gujarat Mineral": "METALS",
  "Orissa Minerals": "METALS",
  "Ashapura Minechem": "METALS",
  "Sandur Manganese": "METALS",
  "Hindalco Industries": "METALS",
  "Maithan Alloys": "METALS",
  "Gravita India": "METALS",
  "Sarda Energy": "METALS",
  "Maharashtra Seamless": "METALS",
  "Kalyani Steels": "METALS",
  "JTL Industries": "METALS",
  "Prakash Industries": "METALS",
  "Usha Martin": "METALS",
  "Sunflag Iron": "METALS",
  "Hisar Metal": "METALS",
  "Manaksia Steels": "METALS",
  "Rhetan TMT": "METALS",
  "Harsha Engineers": "METALS",
  "Hariom Pipe": "METALS",
  "Nupur Recyclers": "METALS",
  "Kalyani Cast-Tech": "METALS",
  "Ratnaveer Precision": "METALS",
  "Shree Marutinandan Tubes": "METALS",
  "Bansal Wire": "METALS",

  //TELECOM
  "Bharti Airtel": "TELECOM",
  "Indus Towers": "TELECOM",
  "Affle 3i": "TELECOM",
  "ITI Ltd": "TELECOM",
  "Astra Microwave": "TELECOM",
  "Avantel": "TELECOM",
  "Bharti Hexacom": "TELECOM",

  //TEXTILE
  "Page Industries": "TEXTILE",
  "KPR Mill": "TEXTILE",
  "Welspun Living": "TEXTILE",
  "Trident Ltd": "TEXTILE",
  "Vardhman Textiles": "TEXTILE",
  "LMW": "TEXTILE",
  "Garware Technical": "TEXTILE",
  "Lux Industries": "TEXTILE",
  "Indo Count": "TEXTILE",
  "Rupa & Company": "TEXTILE",
  "Raymond": "TEXTILE",
  "Go Fashion": "TEXTILE",
  "Vedant Fashions": "TEXTILE",
  "Sai Silks": "TEXTILE",
  "Filatex India": "TEXTILE",
  "Sanathan Textiles": "TEXTILE",
  "Arvind Ltd": "TEXTILE",
  "Mayur Uniquoters": "TEXTILE",
  "Himatsingka Seide": "TEXTILE",
  "Bombay Dyeing": "TEXTILE",
  "Dollar Industries": "TEXTILE",
  "Ganesha Ecosphere": "TEXTILE",
  "Sutlej Textiles": "TEXTILE",
  "Ambika Cotton Mills": "TEXTILE",
  "Century Enka": "TEXTILE",
  "Nitin Spinners": "TEXTILE",
  "Bizotic Commercial": "TEXTILE",
  "Gokaldas Exports": "TEXTILE",
  "Sheela Foam": "TEXTILE",
  "Shanti Spintex": "TEXTILE",
  "Credo Brands": "TEXTILE",
  "United Cotfab": "TEXTILE",

  //TRADING SERVICES
  "Multi Commodity Exchange": "TRADING_SERVICES",
  "Computer Age Management": "TRADING_SERVICES",
  "Indian Energy Exchange": "TRADING_SERVICES",
  "Central Depository Services": "TRADING_SERVICES",
  "BSE Ltd": "TRADING_SERVICES",
  "Kfin Technologies": "TRADING_SERVICES",
  "Angel One": "TRADING_SERVICES",

  //ASSET MANAGEMENT
  "HDFC Asset Management": "AMC",
  "Nippon Life India": "AMC",
  "UTI Asset Management": "AMC",
  "Aditya Birla Sun Life Amc": "AMC",
  "360 One Wam": "AMC",
  "Anand Rathi Wealth": "AMC",
  "Prudent Corporate Advisory": "AMC",
  "DAM Capital Advisors": "AMC",

  ///TRADING
  "Adani Enterprises": "TRADING",
  "Gujarat Gas": "TRADING",
  "Sundram Fasteners": "TRADING",
  "Redington": "TRADING",
  "MMTC": "TRADING",
  "MSTC": "TRADING",

  //TYRES
  "Balkrishna Industries": "TYRES",
  "MRF": "TYRES",
  "Apollo Tyres": "TYRES",
  "CEAT": "TYRES",
  "JK Tyre & Industries": "TYRES",
  "Goodyear India": "TYRES",
  "TVS Srichakra": "TYRES",
  "Tolins Tyres": "TYRES",

  //WATER & WASTE MANAGEMENT
  "Ion Exchange": "WATER_WASTE",
  "Taylormade Renewables": "WATER_WASTE",
  "VA Tech Wabag": "WATER_WASTE",
  "Antony Waste Handling": "WATER_WASTE",
  "Shelter Pharma": "WATER_WASTE",
  "Siyaram Recycling": "WATER_WASTE",
  "GEM Enviro Management": "WATER_WASTE",
  "Enviro Infra Engineers": "WATER_WASTE",
  "Concord Enviro Systems": "WATER_WASTE",

  //RAILWAYS
  "IRCTC": "RAILWAYS",
  "IRFC": "RAILWAYS",
  "Rail Vikas Nigam": "RAILWAYS",
  "BEML": "RAILWAYS",
  "Ircon International": "RAILWAYS",
  "Texmaco Rail": "RAILWAYS",
  "Railtel Corporation": "RAILWAYS",
  "Jupiter Wagons": "RAILWAYS",
  "Titagarh Rail Systems": "RAILWAYS",
  "Concord Control Systems": "RAILWAYS",
  "GPT Infraprojects": "RAILWAYS",
  "Salzer Electronics": "RAILWAYS",
  "Balu Forge Industries": "RAILWAYS",
  "Jayant Infratech": "RAILWAYS",
  "Cosmic CRF": "RAILWAYS",
  "Interglobe Aviation": "RAILWAYS",

  //SOLAR
  "Waaree Energies": "SOLAR",
  "Waaree Renewable": "SOLAR",
  "Sterling and Wilson": "SOLAR",
  "Borosil Renewables": "SOLAR",
  "Gensol Engineering": "SOLAR",
  "Insolation Energy": "SOLAR",
  "WAA Solar": "SOLAR",
  "KPI Green Energy": "SOLAR",
  "Bondada Engineering": "SOLAR",
  "Ahasolar Technologies": "SOLAR",
  "Premier Energies": "SOLAR",
  "Acme Solar Holdings": "SOLAR",

  //PSU
  "Hindustan Aeronautics": "PSU",
  "Bharat Dynamics": "PSU",
  "Bharat Electronics": "PSU",
  "Bharat Heavy Electricals": "PSU",
  "HUDCO": "PSU",
  "Coal India": "PSU",
  "Engineers India": "PSU",
  "Gail (India)": "PSU",
  "GIC of India": "PSU",
  "Hindustan Copper": "PSU",
  "Hindustan Petroleum": "PSU",
  "Bharat Petroleum": "PSU",
  "ONGC": "PSU",
  "Moil Ltd": "PSU",
  "Oil India": "PSU",
  "Indian Oil Corporation": "PSU",
  "NCC Ltd": "PSU",
  "NBCC": "PSU",
  "NHPC": "PSU",
  "NTPC": "PSU",
  "NTPC Green Energy": "PSU",
  "ITI Ltd": "PSU",
  "KIOCL": "PSU",
  "Mangalore Refinery": "PSU",
  "Mishra Dhatu Nigam": "PSU",
  "National Aluminium": "PSU",
  "NLC India": "PSU",
  "India Tourism Dev": "PSU",
  "NMDC": "PSU",
  "Power Finance Corp": "PSU",
  "Power Grid": "PSU",
  "Rashtriya Chemicals": "PSU",
  "REC Ltd": "PSU",
  "Rites Ltd": "PSU",
  "SJVN": "PSU",
  "IREDA": "PSU",

  //DEFENCE
  "Data Patterns": "DEFENCE",
  "Droneacharya": "DEFENCE",
  "ideaForge Technology": "DEFENCE",
  "Paras Defence": "DEFENCE",
  "DCX Systems": "DEFENCE",
  "MTAR Technologies": "DEFENCE",
  "CE Info Systems": "DEFENCE",
  "Azad Engineering": "DEFENCE",
  "Unimech Aerospace": "DEFENCE",
  "Cyient DLM": "DEFENCE",

  //E-COMMERCE
  "Paytm (One 97)": "E_COMMERCE",
  "Cms Info Systems": "E_COMMERCE",
  "PB Fintech": "E_COMMERCE",
  "Eternal Ltd": "E_COMMERCE",
  "Swiggy": "E_COMMERCE",
  "Honasa Consumer": "E_COMMERCE",
  "MobiKwik": "E_COMMERCE",
  "Nykaa (Fsn E-Commerce)": "E_COMMERCE",
  "Meesho": "E_COMMERCE",
  "FirstCry (Brainbees)": "E_COMMERCE",
  "Urban Company": "E_COMMERCE",
  "Mish Designs": "E_COMMERCE",
  "Info Edge": "E_COMMERCE",
  "IndiaMART": "E_COMMERCE",
  "Just Dial": "E_COMMERCE",
  "Nureca": "E_COMMERCE",
  "Sun Tv Network": "E_COMMERCE",
  "Zee Entertainment": "E_COMMERCE",
  "PVR INOX": "E_COMMERCE",
  "Hathway Cable": "E_COMMERCE",
  "Delta Corp": "E_COMMERCE",
  "Saregama India": "E_COMMERCE",
  "DEN Networks": "E_COMMERCE",
  "Wonderla Holidays": "E_COMMERCE",
  "Hindustan Media": "E_COMMERCE"
};

export const sectorColors = {
  "IT": "#818cf8",         // Softer Indigo
  "ALCOHOL": "#fcd34d",    // Warmer Amber
  "API": "#e2db4d",        // Softer Pink
  "AUTO_ANCILLARY": "#bbe585", // Fresher Green
  "NBFC": "#63c1d8",       // Warmer Yellow
  "AGRICULTURE": "#34d399", // Fresher Emerald
  "AUTO": "#f87171",       // Softer Red
  "BANK": "#60a5fa",       // Modern Blue
  "SHIPPING": "#776638",     // Modern Amber
  "FINANCE": "#22d3ee",    // Modern Cyan
  "CABLES": "#fbbf24",      // Modern Amber
  "CONS_DURABLES": "#c035d5", // Softer Rose
  "CRUDE_OIL_GAS": "#3cdf2e", // Modern Orange
  "ELECTRICAL": "#a78bfa", // Softer Violet
  "EDIBLE_OILS": "#fbbf24", // Modern Amber
  "E_COMMERCE": "#f9a8d4",     // Softer Pink
  "EV": "#34d399",         // Fresher Emerald
  "GASES": "#22d3ee",      // Modern Cyan
  "FMCG": "#f87171",       // Softer Red
  "GLASS": "#60a5fa",      // Modern Blue
  "LIFE_INSURANCE": "#fcd34d", // Warmer Amber
  "HOSPITALS": "#c035d5",  // Softer Rose
  "HOTELS": "#fbbf24",     // Modern Amber
  "HOUSING_FINANCE": "#22d3ee", // Modern Cyan
  "NON_ELECTRICAL": "#b677dd", // Modern Amber
  "CASTINGS_FORGINGS": "#72519f", // Softer Pink
  "CEMENT": "#8d8c88",     // Modern Amber
  "CHEMICALS": "#2dd4bf",     // Modern Teal
  "CONSTRUCTION": "#cec7c1",  // Softer Orange
  "CERAMICS": "#9b9890",     // Modern Amber
  "EDUCATION": "#c5df22",     // Modern Amber
  "JEWELLERY": "#f9a8d4",     // Softer Pink
  "PHARMA": "#e2d14f",        // Softer Pink
  "POWER": "#facc15",         // Modern Yellow
  "PETROCHEMICALS": "#22d3ee", // Modern Cyan
  "SHIPPING": "#fbbf24",       // Modern Amber
  "LOGISTICS": "#22d3ee",      // Modern Cyan
  "PLASTIC": "#34d399",        // Fresher Emerald
  "PAINTS": "#f87171",        // Softer Red
  "RATINGS": "#d95245",       // Modern Amber
  "REALTY": "#fbbf24",        // Modern Amber
  "RETAIL": "#f87171",        // Softer Red,
  "TEXTILE": "#c035d5",      // Softer Rose
  "TELECOM": "#60a5fa",      // Modern Blue
  "TRADING_SERVICES": "#22d3ee", // Modern Cyan
  "TRADING": "#fbbf24",       // Modern Amber
  "TYRES": "#f87171",        // Softer Red
  "WATER_WASTE": "#34d399",  // Fresher Emerald
  "RAILWAYS": "#60a5fa",      // Modern Blue
  "SOLAR": "#fbbf24",         // Modern Amber
  "PSU": "#22d3ee",           // Modern Cyan
  "REFRACTORIES": "#a78bfa",  // Softer Violet
  "RUBBER_BELTS": "#34d399", // Fresher Emerald
  "SUGAR_ETHANOL": "#fbbf24", // Modern Amber
  "METALS": "#60a5fa",        // Modern Blue
  "RETAIL_FASHION": "#f9a8d4", // Softer Pink
  "PAPER_CARTELS": "#8b5cf6",   // Modern Violet
  "RETAIL_LEATHER": "#60a5fa", // Modern Blue
  "DEFENCE": "#94a3b8",       // Modern Grey/Slate
  "DIVERSIFIED": "#22d182",   // Modern Amber
  "CONSUMER": "#fda4af",      // Softer Rose
  "DEFAULT": "#475569"        // Medium Slate
};